language: objective-c
os: osx
osx_image: xcode9.3
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod repo update
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild clean test -workspace Example/KingfisherWebP.xcworkspace -scheme KingfisherWebP-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' | xcpretty
- pod lib lint --allow-warnings
